# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_body', models.TextField()),
                ('blog_type', models.CharField(max_length=50)),
                ('blog_timestamp', models.DateTimeField()),
                ('blog_imgurl', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_author', models.CharField(max_length=20, null=True)),
                ('blog_ismarkdown', models.CharField(max_length=1, null=True)),
                ('blog_like', models.IntegerField(null=True)),
                ('blog_clicknum', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-blog_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
